name: "Hello Actions"
description: "Greet yijun"
author: "yijxiang@github.com"

inputs:
  INPUT_MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
